- file:
    path: "{{ tgt }}/{{ item }}"
    state: directory
  with_items:
    - ""
    - zulip-bot
    - zulip-bot/src

- copy:
    src: "{{ repo }}/{{ item }}"
    dest: "{{ tgt }}/{{ item }}"
    mode: 0600
  with_items:
    - zulip-bot/bot.py
    - zulip-bot/src/bridge.py
    - zulip-bot/src/constants.py
    - zulip-bot/src/notifier.py
    - zulip-bot/src/setup.py
    - zulip-bot/src/status.py
    - Makefile
    - poetry.lock
    - pyproject.toml
    - .env

